name = "Windows Delivery Optimization"

[get]
verb = "GET"
uris = ["/msdownload/do/v1/metadata", "/msdownload/do/v1/content"]

[get.client.headers]
Accept = "*/*"
Accept-Encoding = "identity"
Connection = "Keep-Alive"
Pragma = "no-cache"
User-Agent = "Microsoft-Delivery-Optimization/10.0"
X-MS-DO-Client-Version = "10.0.19045.4046"
X-MS-DO-NetworkCost = "Unrestricted"

[get.client.parameters]
branch = "Retail"
os = "10.0.19045.0"
platform = "Windows"

[get.client.message]
location = "header"
name = "X-MS-DO-RequestId"

[[get.client.transforms]]
action = "base64url"

[get.server.headers]
Cache-Control = "private, max-age=0"
Content-Type = "application/json; charset=utf-8"
Server = "Microsoft-HTTPAPI/2.0"
X-MS-DO-CacheState = "miss"

[post]
verb = "POST"
uris = ["/msdownload/do/v1/status", "/msdownload/do/v1/telemetry"]

[post.client.headers]
Accept = "*/*"
Connection = "Keep-Alive"
Content-Type = "application/json; charset=utf-8"
Pragma = "no-cache"
User-Agent = "Microsoft-Delivery-Optimization/10.0"
X-MS-DO-Client-Version = "10.0.19045.4046"

[post.client.parameters]
branch = "Retail"
os = "10.0.19045.0"

[post.client.message]
location = "body"

[[post.client.transforms]]
action = "base64url"

[post.server.headers]
Cache-Control = "no-cache"
Content-Type = "application/json; charset=utf-8"
Server = "Microsoft-HTTPAPI/2.0"
